baseURL: https://example.com
languageCode: en-us
title: Wordsalt
theme: mini

defaultContentLanguage: en

markup:    
  highlight:    
    guessSyntax: true    
    style: emacs    
  tableOfContents:    
    endLevel: 3    
    ordered: false    
    startLevel: 2

social:
  github: https://github.com/wordsalt

params:
  author: Andrew Smith
  bio: Fuck the system.
  # "Used in HTML meat," according to the theme
  description: Fuck the system.

  # RSS is cool, but it puts this massive fucking subscribe button at the top of the page that's completely unnecessary and I can't be fucked to get rid of for now
  enableRSS: false
  # Technically we do have comments, but they're hardcoded... stfu I swear I'm good at my job
  enableComments: false
  enableGoogleAnalytics: false
  # TODO: make sure we actually like TOCs
  showToc: true

