name: build

on:
  # Run on tag/branch creation
  create:
  
  schedule:
   - cron: "0 0 * * *"
 
  # Run manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@master
       with:
         submodules: true
     - name: build
       uses: jakejarvis/hugo-build-action@master
     - name: commit and push
       run: |
         git config --global user.name 'Your Name'
         git config --global user.email 'your-username@users.noreply.github.com'
         git commit -am "Automated report"
         git push
